# kafka configuration
kafka:
  bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  topic:
    resources: resources
  consumer:
    concurrency: 3

# client configuration
resource-service:
  endpoint: http://localhost:8090/api/v1
  accept:
    mime-type: audio/mpeg
song-service:
  endpoint: http://localhost:8091/api/v1
web-client:
  connection:
    timeout: 5000
  response:
    timeout: 5000
  read:
    timeout: 5000
  write:
    timeout: 5000

# retry configuration
retry:
  max:
    attempts: 3
    delay: 500